# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Giuliano Losa
# subtitle: Test
email: giuliano@losa.fr
description: >- # this means to ignore newlines until "baseurl:"
  Giuliano's website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.losa.fr" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "giuliano_losa"
github_username:  "nano-o"
name: "Giuliano Losa"
locale: "en-US"
production: true

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache # needed by minimal-mistakes-jekyll
  # - jekyll-toc
# not needed (or even compatible?) with the minimal-mistakes-jekyll theme:
  # - jekyll-seo-tag
  # - jekyll-og-image
  #
kramdown:
  syntax_highlighter_opts:
    disable : true

author:
  name: "Giuliano Losa"
  bio: "Researcher in distributed computing and formal methods"
  avatar: "/images/painting-cropped.jpg"
  location: Washington State, USA
  links:
    - label: giuliano@losa.fr
      icon: "fa-regular fa-envelope"
      url: mailto:giuliano@losa.fr
    - label: "giuliano_losa"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/giuliano_losa"
    - label: "nano-o"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nano-o"
    - label: "Google Scholar"
      url: "https://scholar.google.com/citations?user=m2jQVgQAAAAJ"
      icon: "fa-brands fa-google-scholar"
    - label: "DBLP"
      url: "https://dblp.uni-trier.de/pid/04/11066.html"
      icon: "fas fa-fw fa-link"
    - label: "SDF Research"
      icon: "fas fa-fw fa-link"
      url: "https://research.stellar.org"
# see https://github.com/mmistakes/minimal-mistakes/issues/324 for other icons

og_image: "/images/painting-cropped.jpg"

footer:
  test

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
include:
  - _pages
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
